# =============================================================================
# AutoInsight AI — Pydantic Data Models (schemas.py)
# Phase 1: Foundation — All Pydantic v2 Strict Models
# =============================================================================
"""
This module defines ALL Pydantic v2 data models for the AutoInsight AI system.

These models serve as the **strict data contracts** between all 8 stages:
  - Stage 1: CSV Ingestion → SchemaInferenceResponse
  - Stage 2: Data Cleaning → CleaningPlan, QualityProfile
  - Stage 3: LangGraph Agent → Relationship, DerivedColumn, UnifiedDataModel
  - Stage 4: Column Engineering → (uses UnifiedDataModel)
  - Stage 5: Report Engine → DataProfile, ReportBundle
  - Stage 6: NLQ Chat → NLQQuery, NLQResponse
  - Stage 7: Frontend → (consumes REST API)
  - Stage 8: Infrastructure → (uses all models)

Key Design Decisions:
  - All models use Pydantic v2 strict mode (validate_default=True)
  - Confidence scores are clamped to [0.0, 1.0] via Field(ge=0.0, le=1.0)
  - UUIDs are auto-generated for all database-bound models
  - Optional fields use Optional[] with None default for flexibility
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator, model_validator


# =============================================================================
# Enumerations
# =============================================================================

class RelationshipType(str, Enum):
    """Types of relationships that can exist between data columns."""
    ONE_TO_ONE = "one-to-one"
    ONE_TO_MANY = "one-to-many"
    MANY_TO_MANY = "many-to-many"
    SELF_REFERENTIAL = "self-referential"
    UNKNOWN = "unknown"


class DataType(str, Enum):
    """Supported data types for column inference and validation."""
    INTEGER = "int"
    FLOAT = "float"
    STRING = "str"
    DATE = "date"
    DATETIME = "datetime"
    BOOLEAN = "boolean"
    CATEGORICAL = "categorical"
    TEXT = "text"
    UNKNOWN = "unknown"


class ConfidenceLevel(str, Enum):
    """Confidence levels mapped from numerical scores for UI display."""
    HIGH = "high"          # 0.90 - 1.00 → Auto-apply (Green)
    MEDIUM = "medium"      # 0.70 - 0.89 → Manual approval (Yellow)
    LOW = "low"            # 0.50 - 0.69 → Review required (Orange)
    VERY_LOW = "very_low"  # < 0.50       → Advisory only (Red)


class PipelineStatus(str, Enum):
    """Pipeline execution status values."""
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PAUSED = "paused"


class UserRole(str, Enum):
    """RBAC roles for the system."""
    ADMIN = "admin"
    ANALYST = "analyst"
    VIEWER = "viewer"


class ReportSectionType(str, Enum):
    """Types of report sections generated by the 8 parallel sub-agents."""
    BUSINESS_UNDERSTANDING = "business_understanding"
    DATA_COLLECTION = "data_collection"
    CLEANING_ANALYSIS = "cleaning_analysis"
    EDA = "exploratory_data_analysis"
    STATISTICAL_ANALYSIS = "statistical_analysis"
    DASHBOARD_VIZ = "dashboard_visualization"
    INSIGHTS = "insights"
    RECOMMENDATIONS = "recommendations"


class ChartType(str, Enum):
    """Supported chart types for auto-generated visualizations."""
    BAR = "bar"
    LINE = "line"
    SCATTER = "scatter"
    HEATMAP = "heatmap"
    BOX = "box"
    PIE = "pie"
    HISTOGRAM = "histogram"
    AREA = "area"
    BUBBLE = "bubble"
    TREEMAP = "treemap"


# =============================================================================
# Stage 1: CSV Ingestion & Schema Inference Models
# =============================================================================

class ColumnInference(BaseModel):
    """
    Schema inference result for a single column from a CSV file.
    Produced by Qwen 2.5 72B in Stage 1.

    Attributes:
        column_name: The original column header from the CSV
        detected_type: Inferred data type for the column
        format_spec: Optional format specification (e.g., date format "%Y-%m-%d")
        confidence: Confidence score [0.0, 1.0] for the type inference
        reasoning: LLM explanation for why this type was chosen
        nullable: Whether the column contains null values
        sample_values: Up to 5 sample values from the CSV for verification
    """
    column_name: str = Field(..., description="Original column header from CSV")
    detected_type: DataType = Field(..., description="Inferred data type")
    format_spec: Optional[str] = Field(None, description="Format spec (e.g., date format)")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score [0.0, 1.0]"
    )
    reasoning: str = Field(..., min_length=1, description="LLM explanation for inference")
    nullable: bool = Field(True, description="Whether column contains nulls")
    sample_values: List[Optional[str]] = Field(
        default_factory=list, max_length=5, description="Up to 5 sample values"
    )

    @field_validator("confidence")
    @classmethod
    def clamp_confidence(cls, v: float) -> float:
        """Clamp confidence to valid range."""
        return max(0.0, min(1.0, v))

    @field_validator("column_name")
    @classmethod
    def validate_column_name(cls, v: str) -> str:
        """Ensure column name is not empty and has reasonable length."""
        if not v or len(v.strip()) == 0:
            raise ValueError("Column name cannot be empty")
        if len(v) > 255:
            raise ValueError("Column name exceeds maximum length (255)")
        return v.strip()


class SchemaInferenceResponse(BaseModel):
    """
    Complete schema inference result for a CSV file.
    Output of Stage 1 — passed as input to Stage 2 (Data Cleaning).

    Attributes:
        columns: List of inferred column schemas
        row_count: Number of rows detected in the CSV
        encoding: Detected file encoding (via chardet)
        detected_delimiter: Detected CSV delimiter character
        has_header: Whether the CSV has a header row
        overall_confidence: Average confidence across all columns
        file_hash: MD5 hash of the original file for caching
        processing_time_ms: Time taken for schema inference
    """
    columns: List[ColumnInference] = Field(
        ..., min_length=1, description="All inferred column schemas"
    )
    row_count: int = Field(..., ge=0, description="Number of rows in CSV")
    encoding: str = Field(default="utf-8", description="Detected file encoding")
    detected_delimiter: str = Field(default=",", description="CSV delimiter character")
    has_header: bool = Field(True, description="Whether CSV has a header row")
    overall_confidence: Optional[float] = Field(
        None, ge=0.0, le=1.0,
        description="Average confidence across all columns (auto-computed if not provided)"
    )
    file_hash: Optional[str] = Field(None, description="MD5 hash for caching")
    processing_time_ms: Optional[int] = Field(None, description="Processing time")

    @model_validator(mode="after")
    def compute_overall_confidence(self) -> "SchemaInferenceResponse":
        """Auto-compute overall confidence from individual column confidences."""
        if self.columns and self.overall_confidence is None:
            self.overall_confidence = round(
                sum(c.confidence for c in self.columns) / len(self.columns),
                4,
            )
        return self


# =============================================================================
# Stage 2: Data Cleaning Models
# =============================================================================

class QualityIssue(BaseModel):
    """
    A single data quality issue detected during profiling.

    Attributes:
        column: The column containing the issue
        issue_type: Type of issue (missing, outlier, duplicate, pii, type_mismatch)
        severity: Severity score [0.0, 1.0]
        details: Human-readable description of the issue
        row_count: Number of affected rows
        suggestion: Recommended cleaning strategy
    """
    column: str = Field(..., description="Column containing the issue")
    issue_type: str = Field(
        ..., description="Type: missing, outlier, duplicate, pii, type_mismatch"
    )
    severity: float = Field(
        ..., ge=0.0, le=1.0, description="Severity score [0.0, 1.0]"
    )
    details: str = Field(..., min_length=1, description="Human-readable description")
    row_count: int = Field(..., ge=0, description="Number of affected rows")
    suggestion: str = Field(..., description="Recommended cleaning strategy")


class QualityProfile(BaseModel):
    """
    Comprehensive data quality profile for a dataset.
    Produced by DataPrep + Polars in Stage 2.

    Attributes:
        columns: Per-column quality metrics
        missing_summary: Summary of missing values across dataset
        outlier_summary: Summary of outlier detection results
        duplicate_summary: Duplicate row detection results
        pii_columns: Columns containing detected PII
        overall_quality_score: Overall data quality score [0.0, 1.0]
    """
    columns: Dict[str, Dict[str, Any]] = Field(
        ..., description="Per-column quality metrics"
    )
    missing_summary: Dict[str, Any] = Field(
        ..., description="Missing value summary"
    )
    outlier_summary: Dict[str, Any] = Field(
        default_factory=dict, description="Outlier detection results"
    )
    duplicate_summary: Dict[str, Any] = Field(
        default_factory=dict, description="Duplicate detection results"
    )
    pii_columns: List[str] = Field(
        default_factory=list, description="Columns with detected PII"
    )
    overall_quality_score: float = Field(
        ..., ge=0.0, le=1.0, description="Overall data quality [0.0, 1.0]"
    )


class CleaningOperation(BaseModel):
    """
    A single cleaning operation to be applied to the dataset.
    Each operation has a confidence score and can be accepted/rejected by the user.

    Attributes:
        column: Target column for the operation
        issue: The issue being addressed
        strategy: Cleaning strategy (impute, mask, cap, remove, transform)
        parameters: Strategy-specific parameters (e.g., fill value)
        confidence: Confidence in this recommendation [0.0, 1.0]
        reasoning: LLM reasoning for recommending this strategy
    """
    column: str = Field(..., description="Target column")
    issue: str = Field(..., description="Issue being addressed")
    strategy: str = Field(
        ..., description="Strategy: impute, mask, cap, remove, transform"
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict, description="Strategy parameters"
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Recommendation confidence"
    )
    reasoning: str = Field(..., description="LLM reasoning for this strategy")


class CleaningPlan(BaseModel):
    """
    Complete cleaning plan generated by the LLM (Qwen 2.5 72B).
    User can accept/reject/modify individual operations.

    Attributes:
        operations: List of cleaning operations to apply
        description: High-level description of the cleaning approach
        estimated_impact: Estimated impact on data quality
    """
    operations: List[CleaningOperation] = Field(
        ..., min_length=1, description="Cleaning operations to apply"
    )
    description: str = Field(
        ..., description="High-level description of the cleaning approach"
    )
    estimated_impact: str = Field(
        ..., description="Estimated impact on data quality"
    )


# =============================================================================
# Stage 3: LangGraph Agent Models (Core of the System)
# =============================================================================

class Relationship(BaseModel):
    """
    A discovered relationship between two columns in the dataset.
    Produced by the LangGraph agent in Stage 3 (reason_step).

    The LLM (Qwen 2.5 72B) validates and filters candidate relationships,
    assigning confidence scores and suggesting visualization types.

    Attributes:
        source_column: The source/reference column
        target_column: The target/dependent column
        relationship_type: Type of relationship between the columns
        confidence: AI confidence score [0.0, 1.0] — MUST be >= 0.65 to pass gate
        description: Human-readable description of the relationship
        chart_hint: Recommended chart type for visualizing this relationship
        correlation_coefficient: Statistical correlation if computed
        analytical_purpose: Business value of understanding this relationship
    """
    source_column: str = Field(..., description="Source/reference column name")
    target_column: str = Field(..., description="Target/dependent column name")
    relationship_type: RelationshipType = Field(
        ..., description="Type of relationship"
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="AI confidence score (must be >= 0.65)"
    )
    description: str = Field(
        ..., min_length=1, description="Human-readable description"
    )
    chart_hint: ChartType = Field(
        ..., description="Recommended chart type for visualization"
    )
    correlation_coefficient: Optional[float] = Field(
        None, description="Statistical correlation if computed"
    )
    analytical_purpose: Optional[str] = Field(
        None, description="Business value of understanding this relationship"
    )

    @field_validator("confidence")
    @classmethod
    def validate_confidence_gate(cls, v: float) -> float:
        """Warn if confidence is below the gate threshold."""
        if v < 0.65:
            import warnings
            warnings.warn(
                f"Relationship confidence {v:.2f} is below gate threshold of 0.65. "
                "This relationship may be filtered out by the validation gate."
            )
        return max(0.0, min(1.0, v))


class DerivedColumn(BaseModel):
    """
    A new column to be derived from existing data using a Polars expression.
    Generated by the LangGraph agent and executed by Stage 4.

    Attributes:
        name: Name for the new derived column
        expression: Polars expression to compute the column (sandboxed eval)
        data_type: Expected data type of the result
        description: Business explanation of what this column represents
        validation_rules: List of validation rules for the derived data
        confidence: AI confidence in this derived column's usefulness
    """
    name: str = Field(
        ..., min_length=1, max_length=255, description="Name for the new column"
    )
    expression: str = Field(
        ..., min_length=1, description="Polars expression (sandboxed eval)"
    )
    data_type: str = Field(
        ..., description="Expected data type of the result"
    )
    description: str = Field(
        ..., min_length=1, description="Business explanation of the column"
    )
    validation_rules: List[str] = Field(
        default_factory=list, description="Validation rules for the data"
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence in usefulness"
    )


class TransformationAudit(BaseModel):
    """
    Audit trail entry for a single transformation operation.
    Every column operation is logged for full data lineage.

    Attributes:
        step: Name of the transformation step
        column: Column(s) affected
        description: What was done
        expression: The expression/code that was applied
        timestamp: When the operation occurred
        status: Whether the operation succeeded or failed
        row_count_before: Row count before transformation
        row_count_after: Row count after transformation
    """
    step: str = Field(..., description="Step name (e.g., 'profile', 'clean', 'derive')")
    column: str = Field(..., description="Column(s) affected")
    description: str = Field(..., description="What was done")
    expression: Optional[str] = Field(None, description="Applied expression")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow, description="When the operation occurred"
    )
    status: str = Field(
        default="completed", description="Status: completed, failed, skipped"
    )
    row_count_before: Optional[int] = Field(None, description="Rows before")
    row_count_after: Optional[int] = Field(None, description="Rows after")


class UnifiedDataModel(BaseModel):
    """
    THE CORE DATA MODEL — Output of Stage 3/4, Input to Stages 5 & 6.
    Represents the complete enriched understanding of the dataset.

    This is passed through the entire system:
      - Stage 3: LangGraph agent produces this
      - Stage 4: Column engineering materializes derived columns
      - Stage 5: Report Engine uses this for report generation
      - Stage 6: NLQ Chat + Dashboard uses this for visualization
      - Stage 7: Frontend consumes this via REST API

    Attributes:
        original_columns: Columns present in the original CSV
        cleaned_columns: Columns after Stage 2 cleaning
        derived_columns: New columns derived by Stage 4
        relationships: Discovered column relationships
        transformation_audit: Full audit trail of all operations
        final_viz_schema: Auto-generated visualization configuration
        recommended_dashboard_layout: Suggested dashboard layout
    """
    original_columns: List[str] = Field(
        ..., min_length=1, description="Original CSV columns"
    )
    cleaned_columns: List[str] = Field(
        ..., description="Columns after Stage 2 cleaning"
    )
    derived_columns: List[DerivedColumn] = Field(
        default_factory=list, description="New columns derived by Stage 4"
    )
    relationships: List[Relationship] = Field(
        default_factory=list, description="Discovered column relationships"
    )
    transformation_audit: List[TransformationAudit] = Field(
        default_factory=list, description="Full audit trail"
    )
    final_viz_schema: Dict[str, Any] = Field(
        default_factory=dict, description="Visualization configuration"
    )
    recommended_dashboard_layout: Dict[str, Any] = Field(
        default_factory=dict, description="Suggested dashboard layout"
    )

    @property
    def total_columns(self) -> int:
        """Total columns including original + derived."""
        return len(self.cleaned_columns) + len(self.derived_columns)

    @property
    def average_relationship_confidence(self) -> float:
        """Average confidence across all discovered relationships."""
        if not self.relationships:
            return 0.0
        return sum(r.confidence for r in self.relationships) / len(self.relationships)


# =============================================================================
# Stage 5: Report Engine Models
# =============================================================================

class DataProfile(BaseModel):
    """
    Deterministic data profile (Phase 1 of Report Engine — Zero LLM cost).
    Pure computation using Polars, SciPy, and NumPy.

    Attributes:
        schema_metadata: Column names, types, null counts, cardinality
        univariate_stats: Mean, median, std, IQR, skew, kurtosis per column
        bivariate_matrix: Pairwise correlation matrix (Pearson)
        trends: Time series patterns (if date columns exist)
        domain_context: Dataset domain classification
    """
    schema_metadata: Dict[str, Any] = Field(
        ..., description="Schema metadata: column names, types, cardinality"
    )
    univariate_stats: Dict[str, Dict[str, float]] = Field(
        ..., description="Per-column univariate statistics"
    )
    bivariate_matrix: Dict[str, Dict[str, float]] = Field(
        ..., description="Pairwise correlation matrix"
    )
    trends: Optional[Dict[str, Any]] = Field(
        None, description="Time series patterns (if applicable)"
    )
    domain_context: Optional[str] = Field(
        None, description="Inferred dataset domain (e.g., 'sales', 'healthcare')"
    )


class ReportSection(BaseModel):
    """
    A single section of the analytical report.
    Produced by one of the 8 parallel sub-agents in Phase 2.

    Attributes:
        section_type: Which sub-agent produced this section
        title: Section title
        content: Section content (markdown-formatted)
        confidence: AI confidence in this section's accuracy
        chart_hints: Optional chart configurations embedded in the section
    """
    section_type: ReportSectionType = Field(
        ..., description="Sub-agent that produced this section"
    )
    title: str = Field(..., min_length=1, description="Section title")
    content: str = Field(..., min_length=1, description="Markdown-formatted content")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence in section accuracy"
    )
    chart_hints: List[Dict[str, Any]] = Field(
        default_factory=list, description="Embedded chart configurations"
    )


class ReportBundle(BaseModel):
    """
    Complete assembled report with all sections and metadata.
    Output of Phase 4 — ready for export and frontend display.

    Attributes:
        report_id: UUID for this report
        title: Report title
        sections: All 8 report sections from the sub-agents
        overall_confidence: Average confidence across all sections
        audit_trail: Full audit trail of report generation
        export_metadata: Metadata for export engines (PDF, HTML, MD, XLSX)
        viz_payload: Complete visualization configuration
        generated_at: When the report was generated
    """
    report_id: str = Field(
        default_factory=lambda: str(uuid4()), description="Unique report identifier"
    )
    title: str = Field(..., min_length=1, description="Report title")
    sections: List[ReportSection] = Field(
        ..., min_length=1, max_length=8, description="All report sections"
    )
    overall_confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Average confidence across all sections"
    )
    audit_trail: List[Dict[str, Any]] = Field(
        default_factory=list, description="Report generation audit trail"
    )
    export_metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Export engine metadata"
    )
    viz_payload: Dict[str, Any] = Field(
        default_factory=dict, description="Complete visualization config"
    )
    generated_at: datetime = Field(
        default_factory=datetime.utcnow, description="Generation timestamp"
    )


# =============================================================================
# Stage 6: NLQ Chat Models
# =============================================================================

class NLQQuery(BaseModel):
    """
    A natural language query from the user.
    Processed by Stage 6 — parsed into SQL/metrics/dimensions by Qwen 2.5 72B.

    Attributes:
        query: The natural language query text
        conversation_id: Conversation thread identifier
        dataset_id: The dataset/UDM to query against
        max_results: Maximum number of results to return
    """
    query: str = Field(
        ..., min_length=1, max_length=1000, description="Natural language query"
    )
    conversation_id: Optional[str] = Field(
        None, description="Conversation thread identifier"
    )
    dataset_id: str = Field(
        ..., description="Dataset/UDM ID to query against"
    )
    max_results: int = Field(
        default=100, ge=1, le=1000, description="Maximum results to return"
    )


class NLQResponse(BaseModel):
    """
    Response to a natural language query.
    Includes both text explanation and optional chart visualization.

    Attributes:
        natural_language_response: Human-readable answer to the query
        sql_generated: The SQL query that was executed
        chart_config: Optional Vega-Lite chart configuration
        results: Raw query results (truncated for display)
        row_count: Number of result rows
        processing_time_ms: Query processing time
        confidence: Confidence in the response accuracy
    """
    natural_language_response: str = Field(
        ..., description="Human-readable answer"
    )
    sql_generated: Optional[str] = Field(
        None, description="The SQL query that was executed"
    )
    chart_config: Optional[Dict[str, Any]] = Field(
        None, description="Vega-Lite chart configuration"
    )
    results: List[Dict[str, Any]] = Field(
        default_factory=list, description="Query results"
    )
    row_count: int = Field(0, ge=0, description="Number of result rows")
    processing_time_ms: Optional[int] = Field(
        None, description="Query processing time"
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence in response accuracy"
    )


# =============================================================================
# API Response Envelope
# =============================================================================

class APIResponse(BaseModel):
    """
    Standard API response envelope for all endpoints.
    Ensures consistent response format across the entire system.

    Attributes:
        status: success or error
        data: The response payload
        meta: Metadata including timestamp and request_id
        errors: List of error messages (if any)
    """
    status: str = Field(
        ..., pattern="^(success|error)$", description="Response status"
    )
    data: Optional[Dict[str, Any]] = Field(
        None, description="Response payload"
    )
    meta: Dict[str, Any] = Field(
        default_factory=lambda: {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "request_id": str(uuid4()),
            "version": "1.0.0",
        },
        description="Response metadata",
    )
    errors: List[str] = Field(
        default_factory=list, description="Error messages"
    )

    @classmethod
    def success(cls, data: Dict[str, Any], **meta_kwargs) -> "APIResponse":
        """Create a success response with the given data."""
        meta = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "request_id": str(uuid4()),
            "version": "1.0.0",
        }
        meta.update(meta_kwargs)
        return cls(status="success", data=data, meta=meta)

    @classmethod
    def error(cls, message: str, status_code: int = 400) -> "APIResponse":
        """Create an error response with the given message."""
        return cls(
            status="error",
            data=None,
            meta={
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "request_id": str(uuid4()),
                "version": "1.0.0",
                "status_code": status_code,
            },
            errors=[message],
        )


# =============================================================================
# Auth & User Models
# =============================================================================

class UserCreate(BaseModel):
    """Request model for creating a new user."""
    email: str = Field(..., pattern=r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
    password: str = Field(..., min_length=8, max_length=128)
    name: str = Field(..., min_length=1, max_length=255)
    role: UserRole = Field(default=UserRole.ANALYST)


class UserResponse(BaseModel):
    """Response model for user data (never includes password hash)."""
    id: str
    email: str
    name: str
    role: UserRole
    created_at: datetime
    is_active: bool = True


class TokenResponse(BaseModel):
    """JWT token response model."""
    access_token: str = Field(..., description="JWT access token")
    refresh_token: str = Field(..., description="JWT refresh token")
    token_type: str = Field(default="bearer")
    expires_in: int = Field(..., description="Token expiry in seconds")


class LoginRequest(BaseModel):
    """Request model for user login."""
    email: str = Field(..., description="User email")
    password: str = Field(..., min_length=1, description="User password")


# =============================================================================
# Celery Task Models
# =============================================================================

class TaskStatus(BaseModel):
    """Status of an async Celery task."""
    task_id: str = Field(..., description="Celery task ID")
    status: PipelineStatus = Field(..., description="Current task status")
    progress: float = Field(
        0.0, ge=0.0, le=100.0, description="Progress percentage"
    )
    result: Optional[Dict[str, Any]] = Field(
        None, description="Task result (if completed)"
    )
    error: Optional[str] = Field(None, description="Error message (if failed)")
    started_at: Optional[datetime] = Field(None, description="When task started")
    completed_at: Optional[datetime] = Field(None, description="When task completed")


# =============================================================================
# Pipeline Models
# =============================================================================

class PipelineRequest(BaseModel):
    """Request to execute the full 4-stage pipeline."""
    file_id: str = Field(..., description="Uploaded file ID")
    llm_provider: str = Field(
        default="groq", pattern="^(groq|ollama)$", description="LLM provider"
    )
    skip_cleaning: bool = Field(
        default=False, description="Skip Stage 2 cleaning if data is clean"
    )


class PipelineResult(BaseModel):
    """Result of a completed pipeline execution."""
    pipeline_id: str = Field(..., description="Pipeline execution ID")
    status: PipelineStatus = Field(..., description="Final status")
    unified_data_model: Optional[UnifiedDataModel] = Field(
        None, description="The complete unified data model"
    )
    stages_completed: List[str] = Field(
        default_factory=list, description="Stages that completed"
    )
    total_processing_time_ms: Optional[int] = Field(
        None, description="Total processing time"
    )
