// ===== HTML Export Template =====
export function generateHtmlExport(report: any): string {
  const sections = report.sections || [];
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.title)} — AutoInsight AI Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1f2937; background: #f9fafb; line-height: 1.6; }
    .container { max-width: 900px; margin: 40px auto; padding: 0 20px; }
    header { background: linear-gradient(135deg, #2563eb, #7c3aed); color: white; padding: 40px; border-radius: 16px; margin-bottom: 32px; }
    header h1 { font-size: 28px; margin-bottom: 8px; }
    header .meta { opacity: 0.9; font-size: 14px; }
    header .confidence { display: inline-block; margin-top: 12px; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: 600; }
    .section { background: white; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .section h2 { font-size: 20px; margin-bottom: 16px; color: #111827; }
    .section .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; margin-bottom: 16px; }
    .section .content { color: #374151; font-size: 15px; }
    .section .content p { margin-bottom: 12px; }
    .section .content ul, .section .content ol { margin-left: 20px; margin-bottom: 12px; }
    .section .content li { margin-bottom: 4px; }
    .section .content strong { color: #111827; }
    footer { text-align: center; color: #9ca3af; font-size: 13px; padding: 32px 0; }
    .confidence-high { background: #d1fae5; color: #065f46; }
    .confidence-med { background: #fef3c7; color: #92400e; }
    .confidence-low { background: #fee2e2; color: #991b1b; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${escapeHtml(report.title)}</h1>
      <div class="meta">
        <span>Generated by AutoInsight AI</span>
        <span> | ${new Date(report.createdAt || Date.now()).toLocaleDateString()}</span>
        <span> | ${sections.length} sections</span>
      </div>
      <div class="confidence ${getConfidenceClass(report.overallConfidence)}">
        Overall Confidence: ${Math.round((report.overallConfidence || 0) * 100)}%
      </div>
    </header>
    
    ${sections.map((s: any) => `
    <div class="section">
      <h2>${escapeHtml(s.title)}</h2>
      <div class="badge ${getConfidenceClass(s.confidence)}">
        ${getConfidenceLabel(s.confidence)} — ${Math.round((s.confidence || 0) * 100)}%
      </div>
      <div class="content">
        ${renderMarkdownAsHtml(s.content || "")}
      </div>
    </div>
    `).join("\n    ")}
    
    <footer>
      <p>AutoInsight AI — AI-Powered Data Analysis Platform</p>
      <p>Report generated on ${new Date().toLocaleString()}</p>
    </footer>
  </div>
</body>
</html>`;
}

// ===== Markdown Export Template =====
export function generateMarkdownExport(report: any): string {
  const sections = report.sections || [];
  
  let md = `# ${report.title}\n\n`;
  md += `> **Generated:** ${new Date(report.createdAt || Date.now()).toLocaleString()}\n`;
  md += `> **Sections:** ${sections.length}\n`;
  md += `> **Overall Confidence:** ${Math.round((report.overallConfidence || 0) * 100)}%\n\n`;
  md += `---\n\n`;

  for (const section of sections) {
    const confidenceLabel = getConfidenceLabel(section.confidence);
    md += `## ${section.title}\n\n`;
    md += `> **Confidence:** ${Math.round((section.confidence || 0) * 100)}% — ${confidenceLabel}\n\n`;
    md += `${section.content || "Analysis in progress."}\n\n`;
    md += `---\n\n`;
  }

  md += `\n*Report generated by AutoInsight AI — ${new Date().toLocaleString()}*\n`;
  return md;
}

// ===== Helpers =====

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function getConfidenceClass(confidence: number): string {
  if (confidence >= 0.7) return "confidence-high";
  if (confidence >= 0.5) return "confidence-med";
  return "confidence-low";
}

function getConfidenceLabel(confidence: number): string {
  if (confidence >= 0.9) return "Auto-Approved";
  if (confidence >= 0.7) return "Manual Approval";
  if (confidence >= 0.5) return "Review Required";
  return "Advisory Only";
}

function renderMarkdownAsHtml(markdown: string): string {
  let html = escapeHtml(markdown);
  
  // Headers
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");
  
  // Bold and italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>");
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.+?)\*/g, "<em>$1</em>");
  
  // Lists
  html = html.replace(/^- (.+)$/gm, "<li>$1</li>");
  html = html.replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>");
  html = html.replace(/^\d+\. (.+)$/gm, "<li>$1</li>");
  html = html.replace(/(?:<li>.*<\/li>\n?)+(?=<)/g, (match) => {
    if (!match.includes("<ol>")) return "<ol>" + match + "</ol>";
    return match;
  });
  
  // Paragraphs
  html = html.replace(/\n\n/g, "</p><p>");
  html = "<p>" + html + "</p>";
  
  // Cleanup
  html = html.replace(/<\/?p><\/?p>/g, "");
  html = html.replace(/<\/ul><p>/g, "</ul><p>");
  html = html.replace(/<\/ol><p>/g, "</ol><p>");
  html = html.replace(/<p><ul>/g, "<ul>");
  html = html.replace(/<p><ol>/g, "<ol>");
  html = html.replace(/<\/ul><\/p>/g, "</ul>");
  html = html.replace(/<\/ol><\/p>/g, "</ol>");
  html = html.replace(/<p><li>/g, "<li>");
  html = html.replace(/<\/li><\/p>/g, "</li>");
  
  return html;
}
